### ISSUE TITLE
Hi can you share pretrained model ? 

### ISSUE THREAD

**Issue by Julius-745** [zhaoyuzhi/Hierarchical-Regression-Network-for-Spectral-Reconstruction-from-RGB-Images#10]
Thanks for your great research.

I want to use your pretrained model but the link in Readme.md is error or removed. Can I get the updated link? Thanks.

**Comment by zhaoyuzhi** [comment]
I have already updated README, please check

**Comment by Julius-745** [comment]
Thanks a lot!
